"""UI constants"""

from PyQt6.QtGui import QFont

MAIN_FONT = QFont("Segoe UI", 11)
TITLE_FONT = QFont("Segoe UI", 24, QFont.Weight.Bold)
SUBTITLE_FONT = QFont("Segoe UI", 14)

PRIMARY_COLOR = "#3E4E5E"
ACCENT_COLOR = "#7E87E1"
ACCENT_HOVER = "#8A93E8"
LIGHT_COLOR = "#E8E8E8"
BG_GRADIENT_TOP = "#3A3A3A"
BG_GRADIENT_BOTTOM = "#2B2B2B"
TEXT_PRIMARY = "#FFFFFF"
TEXT_SECONDARY = "#B8B8B8"
SUCCESS_COLOR = "#66BB6A"
WARNING_COLOR = "#FFA726"
DANGER_COLOR = "#EF5350"
CYAN_ACCENT = "#26C6DA"
